services:
  # Echo MCP Client Service
  echo_mcp_client:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: echo_mcp_client
    ports:
      - "8002:8002"
    environment:
      # Application settings
      - ENVIRONMENT=development
      - DEBUG=true
      - APP_NAME=Echo MCP Client
      - APP_VERSION=1.0.0
      - AGENT_PORT=8002
      # Server connection settings
      - SERVER_HOST=http://host.docker.internal:8000
      - MCP_SERVER_URL=http://host.docker.internal:8000/mcp
      # OpenAI settings
      - OPENAI_API_KEY=${OPENAI_API_KEY:-your_openai_api_key_here}
      # AWS Bedrock settings
      - BEDROCK_REGION=us-east-1
      # Development settings
      - DEVELOPMENT_MODE=true
      - AUTO_GENERATE_TEST_DATA=true
      - VERBOSE_LOGGING=true
      # Logging
      - LOG_LEVEL=INFO
      # CORS settings
      - CORS_ORIGINS=["*"]
      - CORS_ALLOW_CREDENTIALS=true
    volumes:
      - ./src:/app/src:ro # Mount for development hot reload
    networks:
      - echo_mcp_client_network
    healthcheck:
      test:
        [
          "CMD",
          "curl",
          "-f",
          "http://localhost:8002/health"
        ]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s
    restart: unless-stopped

networks:
  echo_mcp_client_network:
    driver: bridge
